language: php

php:
  - 5.2
  - 5.3
  - 5.4
  
before_script:
  - mysql -uroot < tests/test.sql
  - psql -Upostgres -f tests/test.sql

notifications:
  email:
    recipients:
      - codycaughlan@gmail.com
      - me@salimane.com
    on_success: change
    on_failure: always
